name: Build and Push to ACR with OIDC
on:
  # mainブランチにプッシュ時の自動実行
  # push:
  branches:
    - main
  # 手動実行用
  workflow_dispatch:

# Azureと安全に通信するための権限設定
permissions:
  id-token: write
  contents: read

# 変数の定義
env:
  ACR_NAME: myregistry # ACR名（.azurecr.ioなし）
  IMAGE_NAME: myapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # ステップ1: ソースコードの取得
      - name: Checkout repository
        uses: actions/checkout@v4

      # ステップ2: Azureへのログイン
      # ID情報(secrets)を使用して、パスワードを使わずに安全にログインが可能
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ステップ3: イメージの作成と送信
      # Azureコマンドを使用して、クラウド上でDockerイメージをビルドし、ACRに保存
      - name: Build and push to ACR (using azure/cli)
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr build \
              --registry ${{ env.ACR_NAME }} \
              --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
              --image ${{ env.IMAGE_NAME }}:latest \
              --file Dockerfile \
